apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-kube-mysql-alertmanager.rules
  namespace: prometheus
spec:
  groups:
  - name: alertmanager.rules
    rules:
    - alert: MySQLTooManyConnections
      annotations:
        message: |
          MySQL too many connections (> 80%)  `{{ $labels.namespace }}/{{ $labels.service }}`
      expr: avg by (instance) (rate(mysql_global_status_threads_connected[1m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 80
      for: 2m
      labels:
        severity: warning
    - alert: MySQLSlowQuery
      annotations:
        message: |
          MySQL slow queries `{{ $labels.namespace }}/{{ $labels.service }}`
      expr: increase(mysql_global_status_slow_queries[1m]) > 0
      for: 2m
      labels:
        severity: warning
