apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: orderbook
  name: orderbookdb
  namespace: instructor-dev
spec:
  ports:
  - name: "mysql"
    port: 3306
    targetPort: 3306
  selector:
    name: orderbookdb
status:
  loadBalancer: {}
