{
 "title": "Steve Example",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Current Build Health Score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (jenkins_builds_health_score{jenkins_job=\"sre-orderbook/steve\"})"
    }
   ]
  },
  {
   "title": "Build Count Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (jenkins_builds_success_build_count{jenkins_job=\"sre-orderbook/steve\"})"
    }
   ]
  },
  {
   "title": "Failed builds in the last 24 hurs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (jenkins_job) (rate(jenkins_builds_failed_build_count{jenkins_job=\"sre-orderbook/steve\"}[1d]))"
    }
   ]
  },
  {
   "title": "Last Build Result",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_builds_last_build_result{jenkins_job=\"sre-orderbook/steve\"}"
    }
   ]
  },
  {
   "title": "Build Health Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_builds_health_score{jenkins_job=\"sre-orderbook/steve\"}\n"
    }
   ]
  },
  {
   "title": "Jenkins Disk Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_disk_usage_bytes" }
   ]
  },
  {
   "title": "Build Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jenkins_builds_duration_milliseconds_summary_sum{jenkins_job=\"sre-orderbook/steve\"} "
    }
   ]
  },
  {
   "title": "404 per hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum by (all) (rate(nginx_ingress_controller_requests{ exported_namespace=\"sre-example-dev\",status=\"404\"}[1h])))/(sum by (all) (rate(nginx_ingress_controller_requests{exported_namespace=\"sre-example-dev\"}[1h]))))*100 > 50"
    }
   ]
  },
  {
   "title": "Number of Threads Orderbook API",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_threads{namespace=\"sre-example-dev\",container=\"orderbookapi\"}"
    }
   ]
  },
  {
   "title": "OrderBook API CPU Usage Last 10 minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=\"sre-example-dev\",container=\"orderbookapi\"}[10m]))"
    }
   ]
  },
  {
   "title": "Open File Descriptors for OrderBook API",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_file_descriptors{namespace=\"sre-example-dev\",container=\"orderbookapi\"}"
    }
   ]
  },
  {
   "title": "Ingress Path Exists",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ingress) (kube_ingress_path{namespace=\"sre-example-dev\"})"
    }
   ]
  },
  {
   "title": "Total Requests in last hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (all) (rate(nginx_ingress_controller_requests{exported_namespace=\"sre-example-dev\"}[1h]))"
    }
   ]
  },
  {
   "title": "404 Requests in last hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_requests{exported_namespace=\"sre-example-dev\",status=\"404\"}[1h])"
    }
   ]
  },
  {
   "title": "Deployments in last day",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (rate(kube_deployment_created{namespace=\"sre-example-dev\"}[1d]))"
    }
   ]
  },
  {
   "title": "Restart Always Policy Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (kube_pod_restart_policy{namespace=\"sre-example-dev\"})"
    }
   ]
  },
  {
   "title": "Orderbook API Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"sre-example-dev\",app=\"orderbookapi\"} |= \"error\" != \"stderr\""
    }
   ]
  }
 ]
}