apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: instructordevapi
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: instructor
  filterTags:
    pattern: '^instructorapi-dev-(?P<ts>.*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc
